import 'package:flutter/material.dart';

void main() {
  runApp(const FigmaToCodeApp());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCodeApp extends StatelessWidget {
  const FigmaToCodeApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(
        body: ListView(children: [
          FindJobs(),
        ]),
      ),
    );
  }
}

class FindJobs extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: 1440,
          height: 1675,
          clipBehavior: Clip.antiAlias,
          decoration: BoxDecoration(color: Colors.white),
          child: Stack(
            children: [
              Positioned(
                left: 34,
                top: 190,
                child: Container(
                  width: 364,
                  height: 564,
                  decoration: ShapeDecoration(
                    color: Color(0xFFEEEEEE),
                    shape: RoundedRectangleBorder(
                      side: BorderSide(
                        width: 0.50,
                        strokeAlign: BorderSide.strokeAlignOutside,
                        color: Colors.white,
                      ),
                      borderRadius: BorderRadius.circular(45),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 34,
                top: 788,
                child: Container(
                  width: 364,
                  height: 329,
                  decoration: ShapeDecoration(
                    color: Color(0xFFEEEEEE),
                    shape: RoundedRectangleBorder(
                      side: BorderSide(
                        width: 0.50,
                        strokeAlign: BorderSide.strokeAlignOutside,
                        color: Colors.white,
                      ),
                      borderRadius: BorderRadius.circular(45),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 98,
                top: 874,
                child: SizedBox(
                  width: 96,
                  height: 19,
                  child: Text(
                    'Contract Type',
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 12,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w500,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 98,
                top: 953,
                child: SizedBox(
                  width: 110,
                  height: 19,
                  child: Text(
                    'Email Frequency',
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 12,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w500,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 97,
                top: 820,
                child: SizedBox(
                  width: 122,
                  height: 35,
                  child: Text(
                    'Job Alert',
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 24,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w700,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 427,
                top: 190,
                child: Container(
                  width: 937,
                  height: 1107,
                  decoration: ShapeDecoration(
                    color: Color(0xFFEEEEEE),
                    shape: RoundedRectangleBorder(
                      side: BorderSide(
                        width: 0.50,
                        strokeAlign: BorderSide.strokeAlignOutside,
                        color: Colors.white,
                      ),
                      borderRadius: BorderRadius.circular(45),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 456,
                top: 339,
                child: Container(
                  width: 426,
                  height: 281,
                  decoration: ShapeDecoration(
                    color: Color(0xFF130FA6),
                    shape: RoundedRectangleBorder(
                      side: BorderSide(
                        width: 0.50,
                        strokeAlign: BorderSide.strokeAlignOutside,
                        color: Colors.white,
                      ),
                      borderRadius: BorderRadius.circular(45),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 622,
                top: 475,
                child: Container(
                  width: 14,
                  height: 15.90,
                  decoration: ShapeDecoration(
                    image: DecorationImage(
                      image: NetworkImage("https://via.placeholder.com/14x16"),
                      fit: BoxFit.fill,
                    ),
                    shape: RoundedRectangleBorder(
                      side: BorderSide(
                        width: 0.60,
                        strokeAlign: BorderSide.strokeAlignCenter,
                        color: Colors.white,
                      ),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 495,
                top: 476,
                child: Container(
                  width: 24,
                  height: 24,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 5,
                        top: 6,
                        child: Container(
                          width: 14,
                          height: 14,
                          decoration: ShapeDecoration(
                            shape: OvalBorder(
                              side: BorderSide(
                                width: 1,
                                strokeAlign: BorderSide.strokeAlignCenter,
                                color: Colors.white,
                              ),
                            ),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 615,
                top: 508,
                child: Container(
                  width: 27,
                  height: 27,
                  child: Stack(children: [
                  ,
                  ]),
                ),
              ),
              Positioned(
                left: 1009,
                top: 231,
                child: Container(
                  width: 119,
                  height: 65,
                  decoration: ShapeDecoration(
                    color: Color(0xFFD9D9D9),
                    shape: RoundedRectangleBorder(
                      side: BorderSide(
                        width: 0.50,
                        strokeAlign: BorderSide.strokeAlignOutside,
                        color: Colors.white,
                      ),
                      borderRadius: BorderRadius.circular(25),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 489,
                top: 557,
                child: Container(
                  width: 85,
                  height: 29,
                  decoration: ShapeDecoration(
                    color: Color(0xFFD9D9D9),
                    shape: RoundedRectangleBorder(
                      side: BorderSide(
                        width: 0.50,
                        strokeAlign: BorderSide.strokeAlignOutside,
                        color: Colors.white,
                      ),
                      borderRadius: BorderRadius.circular(25),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 1151,
                top: 234,
                child: Container(
                  width: 179,
                  height: 62,
                  decoration: ShapeDecoration(
                    color: Color(0xFFD9D9D9),
                    shape: RoundedRectangleBorder(
                      side: BorderSide(
                        width: 0.50,
                        strokeAlign: BorderSide.strokeAlignOutside,
                        color: Colors.white,
                      ),
                      borderRadius: BorderRadius.circular(25),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 97,
                top: 438,
                child: Container(
                  width: 237,
                  height: 32,
                  decoration: ShapeDecoration(
                    color: Color(0xFFD9D9D9),
                    shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(3)),
                  ),
                ),
              ),
              Positioned(
                left: 97,
                top: 515,
                child: Container(
                  width: 237,
                  height: 32,
                  decoration: ShapeDecoration(
                    color: Color(0xFFD9D9D9),
                    shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(3)),
                  ),
                ),
              ),
              Positioned(
                left: 98,
                top: 899,
                child: Container(
                  width: 237,
                  height: 32,
                  decoration: ShapeDecoration(
                    color: Color(0xFFD9D9D9),
                    shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(3)),
                  ),
                ),
              ),
              Positioned(
                left: 98,
                top: 978,
                child: Container(
                  width: 237,
                  height: 32,
                  decoration: ShapeDecoration(
                    color: Color(0xFFD9D9D9),
                    shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(3)),
                  ),
                ),
              ),
              Positioned(
                left: 97,
                top: 588,
                child: Container(
                  width: 237,
                  height: 32,
                  decoration: ShapeDecoration(
                    color: Color(0xFFD9D9D9),
                    shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(3)),
                  ),
                ),
              ),
              Positioned(
                left: 97,
                top: 412,
                child: SizedBox(
                  width: 51,
                  height: 19,
                  child: Text(
                    'Salary',
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 12,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w500,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 97,
                top: 490,
                child: SizedBox(
                  width: 64,
                  height: 19,
                  child: Text(
                    'Employer',
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 12,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w500,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 97,
                top: 567,
                child: SizedBox(
                  width: 96,
                  height: 19,
                  child: Text(
                    'Contract Type',
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 12,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w500,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 157,
                top: 705,
                child: SizedBox(
                  width: 121,
                  height: 13,
                  child: Text(
                    'Find who you’re looking for.',
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 8,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w500,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 97,
                top: 337,
                child: SizedBox(
                  width: 102,
                  height: 21,
                  child: Text(
                    'Category',
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 12,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w500,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 98,
                top: 222,
                child: SizedBox(
                  width: 157,
                  height: 35,
                  child: Text(
                    'Search Help',
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 24,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w700,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 98,
                top: 265,
                child: SizedBox(
                  width: 126,
                  height: 21,
                  child: Text(
                    'Search for keywords',
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 12,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w500,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 1041,
                top: 249,
                child: SizedBox(
                  width: 63,
                  height: 23,
                  child: Text(
                    'Sort by',
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 16,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w500,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 507,
                top: 563,
                child: SizedBox(
                  width: 59,
                  height: 18,
                  child: Text(
                    'Full Time',
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 12,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w500,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 499,
                top: 517,
                child: Text(
                  'Featured',
                  style: TextStyle(
                    color: Color(0xFF05FF00),
                    fontSize: 16,
                    fontFamily: 'Poppins',
                    fontWeight: FontWeight.w500,
                  ),
                ),
              ),
              Positioned(
                left: 1169,
                top: 251,
                child: SizedBox(
                  width: 144,
                  height: 28,
                  child: Text(
                    'Results per page',
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 16,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w500,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 483,
                top: 242,
                child: SizedBox(
                  width: 139,
                  height: 23,
                  child: Text(
                    'Showing results',
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 16,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w500,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 97,
                top: 286,
                child: Container(
                  width: 237,
                  height: 32,
                  decoration: ShapeDecoration(
                    color: Color(0xFFD9D9D9),
                    shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(3)),
                  ),
                ),
              ),
              Positioned(
                left: 97,
                top: 358,
                child: Container(
                  width: 237,
                  height: 32,
                  decoration: ShapeDecoration(
                    color: Color(0xFFD9D9D9),
                    shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(3)),
                  ),
                ),
              ),
              Positioned(
                left: 155,
                top: 651,
                child: Container(
                  width: 110,
                  height: 34,
                  decoration: ShapeDecoration(
                    color: Color(0xFF130FA6),
                    shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(3)),
                  ),
                ),
              ),
              Positioned(
                left: 162,
                top: 1041,
                child: Container(
                  width: 110,
                  height: 34,
                  decoration: ShapeDecoration(
                    color: Color(0xFF130FA6),
                    shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(3)),
                  ),
                ),
              ),
              Positioned(
                left: 199,
                top: 658,
                child: SizedBox(
                  width: 34,
                  height: 20,
                  child: Text(
                    'Filter',
                    style: TextStyle(
                      color: Colors.white,
                      fontSize: 12,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w500,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 187,
                top: 1048,
                child: SizedBox(
                  width: 68,
                  height: 27,
                  child: Text(
                    'Save Alert',
                    style: TextStyle(
                      color: Colors.white,
                      fontSize: 12,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w500,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 29,
                top: 25,
                child: Container(
                  width: 1376,
                  height: 117,
                  decoration: ShapeDecoration(
                    color: Color(0xFF130FA6),
                    shape: RoundedRectangleBorder(
                      side: BorderSide(width: 0.50),
                      borderRadius: BorderRadius.circular(99),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 1073,
                top: 61,
                child: Container(
                  child: Row(
                    mainAxisSize: MainAxisSize.min,
                    mainAxisAlignment: MainAxisAlignment.start,
                    crossAxisAlignment: CrossAxisAlignment.center,
                    children: [
                      Container(
                        padding: const EdgeInsets.all(10),
                        decoration: ShapeDecoration(
                          shape: RoundedRectangleBorder(
                            side: BorderSide(width: 0.50, color: Colors.white),
                            borderRadius: BorderRadius.circular(8),
                          ),
                        ),
                        child: Row(
                          mainAxisSize: MainAxisSize.min,
                          mainAxisAlignment: MainAxisAlignment.center,
                          crossAxisAlignment: CrossAxisAlignment.center,
                          children: [
                            Text(
                              'Login/Register',
                              style: TextStyle(
                                color: Colors.white,
                                fontSize: 12,
                                fontFamily: 'Poppins',
                                fontWeight: FontWeight.w500,
                              ),
                            ),
                          ],
                        ),
                      ),
                      const SizedBox(width: 49),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 128,
                top: 41,
                child: Container(
                  width: 179,
                  height: 77,
                  decoration: BoxDecoration(
                    image: DecorationImage(
                      image: NetworkImage("https://via.placeholder.com/179x77"),
                      fit: BoxFit.fill,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 417,
                top: 71,
                child: Container(
                  width: 533,
                  height: 18,
                  child: Row(
                    mainAxisSize: MainAxisSize.min,
                    mainAxisAlignment: MainAxisAlignment.start,
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      Text(
                        'Home',
                        style: TextStyle(
                          color: Colors.white,
                          fontSize: 12,
                          fontFamily: 'Poppins',
                          fontWeight: FontWeight.w500,
                        ),
                      ),
                      const SizedBox(width: 30),
                      Text(
                        'Jobs',
                        style: TextStyle(
                          color: Colors.white,
                          fontSize: 12,
                          fontFamily: 'Poppins',
                          fontWeight: FontWeight.w500,
                        ),
                      ),
                      const SizedBox(width: 30),
                      Text(
                        'Employers',
                        style: TextStyle(
                          color: Colors.white,
                          fontSize: 12,
                          fontFamily: 'Poppins',
                          fontWeight: FontWeight.w500,
                        ),
                      ),
                      const SizedBox(width: 30),
                      Text(
                        'Candidates',
                        style: TextStyle(
                          color: Colors.white,
                          fontSize: 12,
                          fontFamily: 'Poppins',
                          fontWeight: FontWeight.w500,
                        ),
                      ),
                      const SizedBox(width: 30),
                      Text(
                        'Suppliers',
                        style: TextStyle(
                          color: Colors.white,
                          fontSize: 12,
                          fontFamily: 'Poppins',
                          fontWeight: FontWeight.w500,
                        ),
                      ),
                      const SizedBox(width: 30),
                      Text(
                        'Blog',
                        style: TextStyle(
                          color: Colors.white,
                          fontSize: 12,
                          fontFamily: 'Poppins',
                          fontWeight: FontWeight.w500,
                        ),
                      ),
                      const SizedBox(width: 30),
                      Text(
                        'Help',
                        style: TextStyle(
                          color: Colors.white,
                          fontSize: 12,
                          fontFamily: 'Poppins',
                          fontWeight: FontWeight.w500,
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 495,
                top: 367,
                child: Container(
                  width: 89,
                  height: 89,
                  decoration: ShapeDecoration(
                    color: Colors.white,
                    shape: OvalBorder(),
                  ),
                ),
              ),
              Positioned(
                left: 618,
                top: 365,
                child: SizedBox(
                  width: 89,
                  height: 57,
                  child: Text(
                    'Plumbing\nExpert',
                    style: TextStyle(
                      color: Colors.white,
                      fontSize: 16,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w700,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 659,
                top: 474,
                child: SizedBox(
                  width: 60,
                  height: 21,
                  child: Text(
                    'Kiwatule',
                    style: TextStyle(
                      color: Colors.white,
                      fontSize: 12,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w500,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 531,
                top: 474,
                child: SizedBox(
                  width: 42,
                  height: 20,
                  child: Text(
                    '2 days to go',
                    style: TextStyle(
                      color: Colors.white,
                      fontSize: 12,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w500,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 659,
                top: 512,
                child: SizedBox(
                  width: 55,
                  height: 20,
                  child: Text(
                    'Design',
                    style: TextStyle(
                      color: Colors.white,
                      fontSize: 12,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w500,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 659,
                top: 436,
                child: SizedBox(
                  width: 135,
                  height: 24,
                  child: Text(
                    'UGX. 550,000/month',
                    style: TextStyle(
                      color: Colors.white,
                      fontSize: 12,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w500,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 23,
                top: 1335,
                child: Container(
                  width: 1382,
                  height: 315,
                  decoration: ShapeDecoration(
                    color: Color(0xFF130FA6),
                    shape: RoundedRectangleBorder(
                      side: BorderSide(width: 0.50),
                      borderRadius: BorderRadius.circular(12),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 1165.66,
                top: 1227.82,
                child: Container(
                  width: 70.19,
                  height: 10.81,
                  child: Stack(children: [
                  ,
                  ]),
                ),
              ),
              Positioned(
                left: 445,
                top: 1549,
                child: SizedBox(
                  width: 106.28,
                  child: Text(
                    '+256 782 898 987',
                    style: TextStyle(
                      color: Colors.white,
                      fontSize: 12,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w400,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 450,
                top: 1521,
                child: SizedBox(
                  width: 65.17,
                  child: Text(
                    'Call Us on;',
                    style: TextStyle(
                      color: Colors.white,
                      fontSize: 12,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w600,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 1073,
                top: 1434,
                child: SizedBox(
                  width: 72.19,
                  height: 80,
                  child: Text(
                    'Contact Us\nAbout Us\nTerms\nFAQ',
                    style: TextStyle(
                      color: Colors.white,
                      fontSize: 13,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w400,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 1073,
                top: 1387,
                child: SizedBox(
                  width: 110.29,
                  height: 36,
                  child: Text(
                    'About Us',
                    style: TextStyle(
                      color: Colors.white,
                      fontSize: 24,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w600,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 455,
                top: 1433,
                child: SizedBox(
                  width: 185.49,
                  height: 60,
                  child: Text(
                    'Browse Jobs\nCheck out fellow candidates\nBrowse Employers',
                    style: TextStyle(
                      color: Colors.white,
                      fontSize: 13,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w400,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 453,
                top: 1387,
                child: SizedBox(
                  width: 187.50,
                  height: 36,
                  child: Text(
                    'For Candidates',
                    style: TextStyle(
                      color: Colors.white,
                      fontSize: 24,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w600,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 742,
                top: 1387,
                child: SizedBox(
                  width: 172.46,
                  height: 36,
                  child: Text(
                    'For Employers',
                    style: TextStyle(
                      color: Colors.white,
                      fontSize: 24,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w600,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 739,
                top: 1434,
                child: SizedBox(
                  width: 180.48,
                  height: 60,
                  child: Text(
                    'Browse candidates\nPost a job\nCheck out fellow employers',
                    style: TextStyle(
                      color: Colors.white,
                      fontSize: 13,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w400,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 139,
                top: 1444,
                child: SizedBox(
                  width: 206.55,
                  height: 60,
                  child: Text(
                    '328 Lumumba Avenue, \nGreater Kampala 3051, Uganda.\nsupport@buildup.cloud',
                    style: TextStyle(
                      color: Colors.white,
                      fontSize: 13,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w400,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 128,
                top: 1366,
                child: Container(
                  width: 105,
                  height: 78,
                  decoration: BoxDecoration(
                    image: DecorationImage(
                      image: NetworkImage("https://via.placeholder.com/105x78"),
                      fit: BoxFit.fill,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 128,
                top: 1588,
                child: Container(
                  width: 1107.84,
                  height: 20.96,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 15.04,
                        top: 2.96,
                        child: SizedBox(
                          width: 197.52,
                          height: 18,
                          child: Text(
                            '2023 Buildup. All Rights Reserved.',
                            style: TextStyle(
                              color: Colors.white,
                              fontSize: 12,
                              fontFamily: 'Poppins',
                              fontWeight: FontWeight.w400,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 0,
                        top: 6.96,
                        child: Container(
                          width: 10.03,
                          height: 11,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 2.01,
                                top: 0,
                                child: SizedBox(
                                  width: 6.02,
                                  height: 11,
                                  child: Text(
                                    'C',
                                    textAlign: TextAlign.center,
                                    style: TextStyle(
                                      color: Colors.white,
                                      fontSize: 8,
                                      fontFamily: 'Poppins',
                                      fontWeight: FontWeight.w400,
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 0,
                                top: 1,
                                child: Container(
                                  width: 10.03,
                                  height: 10,
                                  decoration: ShapeDecoration(
                                    shape: OvalBorder(
                                      side: BorderSide(width: 0.10, color: Colors.white),
                                    ),
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 815,
                top: 368,
                child: Container(
                  width: 28,
                  height: 26,
                  child: Stack(children: [
                  ,
                  ]),
                ),
              ),
              Positioned(
                left: 618,
                top: 434,
                child: Container(
                  width: 24,
                  height: 24,
                  child: Stack(children: [
                  ,
                  ]),
                ),
              ),
              Positioned(
                left: 907,
                top: 339,
                child: Container(
                  width: 426,
                  height: 281,
                  decoration: ShapeDecoration(
                    color: Color(0xFF130FA6),
                    shape: RoundedRectangleBorder(
                      side: BorderSide(
                        width: 0.50,
                        strokeAlign: BorderSide.strokeAlignOutside,
                        color: Colors.white,
                      ),
                      borderRadius: BorderRadius.circular(45),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 951,
                top: 476,
                child: Container(
                  width: 24,
                  height: 24,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 5,
                        top: 6,
                        child: Container(
                          width: 14,
                          height: 14,
                          decoration: ShapeDecoration(
                            shape: OvalBorder(
                              side: BorderSide(
                                width: 1,
                                strokeAlign: BorderSide.strokeAlignCenter,
                                color: Colors.white,
                              ),
                            ),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 1071,
                top: 508,
                child: Container(
                  width: 27,
                  height: 27,
                  child: Stack(children: [
                  ,
                  ]),
                ),
              ),
              Positioned(
                left: 1046,
                top: 557,
                child: Container(
                  width: 74,
                  height: 29,
                  decoration: ShapeDecoration(
                    color: Color(0xFFEDBE45),
                    shape: RoundedRectangleBorder(
                      side: BorderSide(
                        width: 0.50,
                        strokeAlign: BorderSide.strokeAlignOutside,
                        color: Colors.white,
                      ),
                      borderRadius: BorderRadius.circular(25),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 945,
                top: 557,
                child: Container(
                  width: 85,
                  height: 29,
                  decoration: ShapeDecoration(
                    color: Color(0xFFD9D9D9),
                    shape: RoundedRectangleBorder(
                      side: BorderSide(
                        width: 0.50,
                        strokeAlign: BorderSide.strokeAlignOutside,
                        color: Colors.white,
                      ),
                      borderRadius: BorderRadius.circular(25),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 963,
                top: 563,
                child: SizedBox(
                  width: 59,
                  height: 18,
                  child: Text(
                    'Full Time',
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 12,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w500,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 1063,
                top: 563,
                child: SizedBox(
                  width: 46,
                  height: 18,
                  child: Text(
                    'Urgent',
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 12,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w500,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 955,
                top: 517,
                child: Text(
                  'Featured',
                  style: TextStyle(
                    color: Color(0xFF05FF00),
                    fontSize: 16,
                    fontFamily: 'Poppins',
                    fontWeight: FontWeight.w500,
                  ),
                ),
              ),
              Positioned(
                left: 951,
                top: 367,
                child: Container(
                  width: 89,
                  height: 89,
                  decoration: ShapeDecoration(
                    color: Colors.white,
                    shape: OvalBorder(),
                  ),
                ),
              ),
              Positioned(
                left: 1074,
                top: 365,
                child: SizedBox(
                  width: 89,
                  height: 57,
                  child: Text(
                    'Plumbing\nExpert',
                    style: TextStyle(
                      color: Colors.white,
                      fontSize: 16,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w700,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 1115,
                top: 474,
                child: SizedBox(
                  width: 60,
                  height: 21,
                  child: Text(
                    'Kiwatule',
                    style: TextStyle(
                      color: Colors.white,
                      fontSize: 12,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w500,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 987,
                top: 474,
                child: SizedBox(
                  width: 42,
                  height: 20,
                  child: Text(
                    '2 days to go',
                    style: TextStyle(
                      color: Colors.white,
                      fontSize: 12,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w500,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 1115,
                top: 512,
                child: SizedBox(
                  width: 55,
                  height: 20,
                  child: Text(
                    'Design',
                    style: TextStyle(
                      color: Colors.white,
                      fontSize: 12,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w500,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 1115,
                top: 436,
                child: SizedBox(
                  width: 135,
                  height: 24,
                  child: Text(
                    'UGX. 550,000/month',
                    style: TextStyle(
                      color: Colors.white,
                      fontSize: 12,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w500,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 1267,
                top: 365,
                child: Container(
                  width: 28,
                  height: 26,
                  child: Stack(children: [
                  ,
                  ]),
                ),
              ),
              Positioned(
                left: 1078,
                top: 475,
                child: Container(
                  width: 14,
                  height: 15.90,
                  decoration: ShapeDecoration(
                    image: DecorationImage(
                      image: NetworkImage("https://via.placeholder.com/14x16"),
                      fit: BoxFit.fill,
                    ),
                    shape: RoundedRectangleBorder(
                      side: BorderSide(
                        width: 0.60,
                        strokeAlign: BorderSide.strokeAlignCenter,
                        color: Colors.white,
                      ),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 1074,
                top: 434,
                child: Container(
                  width: 24,
                  height: 24,
                  child: Stack(children: [
                  ,
                  ]),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}